# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Aeyanr微博' do
use_frameworks!

pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 4.0.0'
pod 'SVProgressHUD', '~> 2.1.2'
pod ’SnapKit’
pod ‘MJRefresh’

end
